# site settings

title: Subhadeep Koley
description: A curious student; an aspiring roboticist
taglong: A curious student; an aspiring roboticist
tagshort: Jekyll theme
url: https://cvless.netlify.app
baseurl: ""
permalink: pretty
repo: https://github.com/wickedticket/wickedticket.github.io

# author settings

author:
  name: Subhadeep Koley
  email: ksubhadeepwork@gmail.com
photo: /assets/jpg/sqfin.jpg

# social media links

social:
  facebook: username
  github: username
  instagram: pinkvoid305
  linkedin: Subhadeep Koley
  stackoverflow: 0000000/username
  twitter: username

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
